name: my_prayer
description: A prayer journal app
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  supabase_flutter: ^2.8.4
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 

  assets:
    - .env